server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    #localhost
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    #username: root
    #password:

    #EC2
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lucete-db:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
<<<<<<< Updated upstream
    password: "lucete1347"

=======
    password: 'tkdlvjwm12@'
>>>>>>> Stashed changes
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 719668423695-4jmaf2s2t32pef24b4bm3vhmrd15to33.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile