server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password:

    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://lucete-db:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    #username: root
    #password: "lucete1347"

  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: 1234