naver:
  client:
    id: aMuXCedmINxvC1kGGYlF
    secret: jxdtkbg1Di
server:
  port: 8080
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
spring:
  datasource:
    #localhost
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: "tkdlvjwm12@"

    #EC2
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://lucete-db:3306/lucete?createDatabaseIfNotExist=True&serverTimeZone=UTC&CharacterEncoding=UTF-8
    #username: root
    #password: "lucete1347"
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 719668423695-4jmaf2s2t32pef24b4bm3vhmrd15to33.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
          naver:
            client-id: aMuXCedmINxvC1kGGYlF
            client-secret: jxdtkbg1Di
            client-name: Naver
            redirect_uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 687a5304ec26939601ea7093996f5bb9
            client-secret: PJXwt7kQ34VuWlG2ffmrDgHzcITNxTyf
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id